name: practicum_project_1
channels:
  - bioconda
  - conda-forge
dependencies:
  - bwa=0.7.19=h7f84b70_1
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.15.0=h37eeddb_1
  - freetype=2.14.1=h694c41f_0
  - igv=2.19.7=h33ea123_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - liblzma=5.8.1=hd471939_2
  - libmpdec=4.0.0=h6e16a3a_0
  - libpng=1.6.50=h84aeda2_1
  - libsqlite=3.51.0=h86bffb9_0
  - libzlib=1.3.1=hd23fc13_2
  - ncurses=6.5=h0622a9a_3
  - openjdk=21.0.9=h2014cc5_0
  - openssl=3.5.4=h230baf5_0
  - perl=5.32.1=7_h10d778d_perl5
  - pip=25.2=pyh145f28c_0
  - python=3.14.0=hf88997e_102_cp314
  - python_abi=3.14=8_cp314
  - readline=8.2=h7cca4af_2
  - samtools=0.1.19=ha21ef43_14
  - seqkit=2.10.1=h193322a_0
  - snpeff=5.3.0a=hdfd78af_1
  - snpsift=5.3.0a=hdfd78af_0
  - tk=8.6.13=hf689a15_2
  - trimmomatic=0.40=hdfd78af_0
  - tzdata=2025b=h78e105d_0
  - varscan=2.4.6=hdfd78af_0
  - zlib=1.3.1=hd23fc13_2
  - zstd=1.5.7=h8210216_2
prefix: /Users/andrejnekrasov/mambaforge/envs/practicum_project_1
