name: practicum_project_1
channels:
  - bioconda
  - conda-forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - brotli-python=1.2.0=py314hd4d9bf7_0
  - bwa=0.7.19=h7f84b70_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h8ca4d5a_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - cpython=3.14.0=py314hd8ed1ab_102
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.15.0=h37eeddb_1
  - freetype=2.14.1=h694c41f_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h9f635df_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.14.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - igv=2.19.7=h33ea123_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kaleido-core=0.2.1=h0d85af4_0
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libblas=3.9.0=38_he492b99_openblas
  - libcblas=3.9.0=38_h9b27e0a_openblas
  - libcurl=8.17.0=h7dd4100_0
  - libcxx=21.1.5=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libiconv=1.18=h57a12c2_2
  - libidn2=2.3.8=h13f126c_1
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.9.0=38_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libmpdec=4.0.0=h6e16a3a_0
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_3
  - libpng=1.6.50=h84aeda2_1
  - libsqlite=3.51.0=h86bffb9_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.1=ha0a348c_1
  - libunistring=0.9.10=h0d85af4_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.5=h472b3d1_0
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - mathjax=2.7.7=h694c41f_3
  - mdurl=0.1.2=pyhd8ed1ab_1
  - multiqc=1.32=pyhdfd78af_1
  - narwhals=2.11.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h0622a9a_3
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.4=py314hf08249b_0
  - openjdk=21.0.9=h2014cc5_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hc4308db_1
  - pcre2=10.45=hf733adb_0
  - perl=5.32.1=7_h10d778d_perl5
  - pillow=12.0.0=py314h0a84944_0
  - pip=25.2=pyh145f28c_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - polars=1.35.1=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.35.1=py310hfb6bc98_0
  - polars-runtime-compat=1.35.1=py310h471337c_0
  - pthread-stubs=0.4=h00291cd_1002
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py314ha7b6dee_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=hf88997e_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.14.0=h4df99d1_102
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=pyh7db6752_0
  - readline=8.2=h7cca4af_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py314h6482030_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.4=pyhd8ed1ab_0
  - rpds-py=0.28.0=py314ha7b6dee_2
  - samtools=1.22.1=ha21ef43_0
  - seqkit=2.10.1=h193322a_0
  - six=1.17.0=pyhe01879c_1
  - snpeff=5.3.0a=hdfd78af_1
  - snpsift=5.3.0a=hdfd78af_0
  - spectra=0.0.11=pyhd8ed1ab_2
  - tiktoken=0.12.0=py314h0484ab5_2
  - tk=8.6.13=hf689a15_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - trimmomatic=0.40=hdfd78af_0
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - varscan=2.4.6=hdfd78af_0
  - wget=1.25.0=hfb6e5ea_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - yaml=0.2.5=h4132b18_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zlib-ng=2.2.5=h55e386d_0
  - zstandard=0.25.0=py314hd1e8ddb_1
  - zstd=1.5.7=h8210216_2
  - pip:
      - tabulate==0.9.0
